name: Sanity

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install --upgrade -e .
          python3 -m pip install --upgrade .[test]
      - name: Test with pytest
        run: |
          make test-only
      - uses: psf/black@stable
        with:
          options: "--check"
          src: "."
          use_pyproject: true
